# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: "ai@cam"
title: ai@cam
description: >- # this means to ignore newlines until "baseurl:"
  ai@cam is the University of Cambridge’s mission to drive a new wave of AI innovation that delivers public value.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ai.cam.ac.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ai_cam_mission
github_username: ai-cam
permalinks: pretty

# Collections
collections:
  blog:
    output: true
  news:
    output: true
  events:
    output: true
  team:
    output: true
  researchers:
    output: true
  research:
    output: true
  projects:
    output: true
  opportunities:
    output: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-redirect-from
 sass:
  sass_dir: _sass
  style: compressed
  sourcemap: always

# Add any other configuration options as needed

# SEO settings
social:
  name: AI@CAM
  links:
    - https://twitter.com/ai_cam_mission

paginate: 9
paginate_path: "/page/:num/"
# for paginate-v2 (not supported by github pages)
# pagination:
#   enabled: true
#   per_page: 9
#   permalink: "/page/:num/"
#   title: ":title"
#   limit: 0
#   sort_field: "date"
#   sort_reverse: true
#   trail:
#     before: 2
#     after: 2
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
