site_logo: /assets/uploads/logo.png
site_logo_white: /assets/uploads/logo-white.png
footer_description: AI for science, citizens, and society.
uoc_details:
  logo: /assets/uploads/cambridge-university.png
  link: https://www.cam.ac.uk/
social_details:
  twitter_link: https://x.com/ai_cam_mission
  facebook_link: https://www.facebook.com/cambridge.university
  instagram_link: https://www.instagram.com/cambridgeuniversity/
